const CREATE_RESTAURENT_REQUEST = "CREATE_RESTAURENT_REQUEST";
const CREATE_RESTAURENT_SUCCESS = "CREATE_RESTAURENT_SUCCESS";
const CREATE_RESTAURENT_FAILURE = "CREATE_RESTAURENT_FAILURE";

const GET_ALL_RESATURENTS_REQUEST = "GET_ALL_RESATURENTS_REQUEST";
const GET_ALL_RESATURENTS_SUCCESS = "GET_ALL_RESATURENTS_SUCCESS";
const GET_ALL_RESATURENTS_FAILURE = "GET_ALL_RESATURENTS_FAILURE";

const DELETE_RESTAURENT_REQUEST = "DELETE_RESTAURENT_REQUEST";
const DELETE_RESTAURENT_SUCCESS = "DELETE_RESTAURENT_SUCCESS";
const DELETE_RESTAURENT_FAILURE = "DELETE_RESTAURENT_FAILURE";

const UPDATE_RESTAURENT_REQUEST = "UPDATE_RESTAURENT_REQUEST";
const UPDATE_RESTAURENT_SUCCESS = "UPDATE_RESTAURENT_SUCCESS";
const UPDATE_RESTAURENT_FAILURE = "UPDATE_RESTAURENT_FAILURE";

const GET_RESTAURENT_BY_ID_REQUEST = "GET_RESTAURENT_BY_ID_REQUEST";
const GET_RESTAURENT_BY_ID_SUCCESS = "GET_RESTAURENT_BY_ID_SUCCESS";
const GET_RESTAURENT_BY_ID_FAILURE = "GET_RESTAURENT_BY_ID_FAILURE";

const GET_RESTAURENT_BY_USER_ID_REQUEST = "GET_RESTAURENT_BY_USER_ID_REQUEST";
const GET_RESTAURENT_BY_USER_ID_SUCCESS = "GET_RESTAURENT_BY_USER_ID_SUCCESS";
const GET_RESTAURENT_BY_USER_ID_FAILURE = "GET_RESTAURENT_BY_USER_ID_FAILURE";

const UPDATE_RESTAURENT_STATUS_REQUEST = "UPDATE_RESTAURENT_STATUS_REQUEST";
const UPDATE_RESTAURENT_STATUS_SUCCESS = "UPDATE_RESTAURENT_STATUS_SUCCESS";
const UPDATE_RESTAURENT_STATUS_FAILURE = "UPDATE_RESTAURENT_STATUS_FAILURE";

const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

const GET_RESTAURENTS_EVENTS_REQUEST = "GET_RESTAURENTS_EVENTS_REQUEST";
const GET_RESTAURENTS_EVENTS_SUCCESS = "GET_RESTAURENTS_EVENTS_SUCCESS";
const GET_RESTAURENTS_EVENTS_FAILURE = "GET_RESTAURENTS_EVENTS_FAILURE";

const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

const GET_RESTAURENTS_CATEGORY_REQUEST = "GET_RESTAURENTS_CATEGORY_REQUEST";
const GET_RESTAURENTS_CATEGORY_SUCCESS = "GET_RESTAURENTS_CATEGORY_SUCCESS";
const GET_RESTAURENTS_CATEGORY_FAILURE = "GET_RESTAURENTS_CATEGORY_FAILURE";
