export const CREATE_EVENT_REQUEST = 'CREATE_EVENT_REQUEST';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const GET_RESTAURANT_EVENT_REQUEST = 'GET_RESTAURANT_EVENT_REQUEST';
export const GET_RESTAURANT_EVENT_SUCCESS = 'GET_RESTAURANT_EVENT_SUCCESS';
export const GET_RESTAURANT_EVENT_FAILURE = 'GET_RESTAURANT_EVENT_FAILURE';

export const DELETE_RESTAURANT_EVENT_REQUEST = 'DELETE_RESTAURANT_EVENT_REQUEST';
export const DELETE_RESTAURANT_EVENT_SUCCESS = 'DELETE_RESTAURANT_EVENT_SUCCESS';
export const DELETE_RESTAURANT_EVENT_FAILURE = 'DELETE_RESTAURANT_EVENT_FAILURE';

export const GET_EVENTS_BY_ALL_RESTAURANT_REQUEST = "GET_EVENTS_BY_ALL_RESTAURANT_REQUEST";
export const GET_EVENTS_BY_ALL_RESTAURANT_SUCCESS = "GET_EVENTS_BY_ALL_RESTAURANT_SUCCESS";
export const GET_EVENTS_BY_ALL_RESTAURANT_FAILURE = "GET_EVENTS_BY_ALL_RESTAURANT_FAILURE";
